// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

/**
 * @param {string} title
 * @param {string} message
 * @returns {$CancellablePromise<void>}
 */
export function ShowErrorDialog(title, message) {
    return $Call.ByID(855167816, title, message);
}

/**
 * @param {string} title
 * @param {string} message
 * @returns {$CancellablePromise<void>}
 */
export function ShowInfoDialog(title, message) {
    return $Call.ByID(1728111726, title, message);
}

/**
 * @param {string} title
 * @param {string} message
 * @returns {$CancellablePromise<void>}
 */
export function ShowWarningDialog(title, message) {
    return $Call.ByID(1789472882, title, message);
}
