// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * FileManagerService is a service for managing files
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * GetOperatingSystem simply returns the OS as a string.
 * https://stackoverflow.com/questions/20728767/all-possible-goos-value
 * @returns {$CancellablePromise<$models.Result<$models.OperatingSystem>>}
 */
export function GetOperatingSystem() {
    return $Call.ByID(3299187408).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * GetPathAtIndex returns the absolute path corresponding to a breadcrumb index
 * @param {string} fullPath
 * @param {number} index
 * @returns {$CancellablePromise<$models.Result<string>>}
 */
export function GetPathAtIndex(fullPath, index) {
    return $Call.ByID(1690715716, fullPath, index).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @param {string} p
 * @returns {$CancellablePromise<$models.Result<$models.PathInfo>>}
 */
export function GetPathInfo(p) {
    return $Call.ByID(3749126181, p).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * ListDirectory lists the contents of a directory.
 * @param {string} dirPath
 * @returns {$CancellablePromise<$models.Result<$models.DirectoryContents>>}
 */
export function ListDirectory(dirPath) {
    return $Call.ByID(1744058245, dirPath).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * @param {string} filePath
 * @returns {$CancellablePromise<$models.Result<string>>}
 */
export function OpenFileWithDefaultApp(filePath) {
    return $Call.ByID(2060842792, filePath).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

// Private type creation functions
const $$createType0 = $models.Result.createFrom($Create.Any);
const $$createType1 = $models.Result.createFrom($Create.Any);
const $$createType2 = $models.PathInfo.createFrom;
const $$createType3 = $models.Result.createFrom($$createType2);
const $$createType4 = $models.DirectoryContents.createFrom;
const $$createType5 = $models.Result.createFrom($$createType4);
