// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * FileManagerService is a service for managing files
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * *
 * 
 * 	targetDir: destination directory
 * 	files: list of source file/directory paths to copy
 * 
 * *
 * @param {string} targetDir
 * @param {string[]} files
 * @returns {$CancellablePromise<$models.Result<string>>}
 */
export function CopyFiles(targetDir, files) {
    return $Call.ByID(1021438870, targetDir, files).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @returns {$CancellablePromise<$models.Result<string>>}
 */
export function GetInitialPath() {
    return $Call.ByID(2587646473).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * GetOperatingSystem simply returns the OS as a string.
 * https://stackoverflow.com/questions/20728767/all-possible-goos-value
 * @returns {$CancellablePromise<$models.Result<$models.OperatingSystem>>}
 */
export function GetOperatingSystem() {
    return $Call.ByID(3299187408).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * GetPathAtIndex returns the absolute path corresponding to a breadcrumb index
 * @param {string} fullPath
 * @param {number} index
 * @returns {$CancellablePromise<$models.Result<string>>}
 */
export function GetPathAtIndex(fullPath, index) {
    return $Call.ByID(1690715716, fullPath, index).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @param {string} p
 * @returns {$CancellablePromise<$models.Result<$models.PathInfo>>}
 */
export function GetPathInfo(p) {
    return $Call.ByID(3749126181, p).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * Sidebar Shortcuts
 * @returns {$CancellablePromise<$models.Result<$models.Shortcut[]>>}
 */
export function GetShortcuts() {
    return $Call.ByID(3114594017).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType6($result);
    }));
}

/**
 * ListDirectory lists the contents of a directory.
 * @param {string} dirPath
 * @returns {$CancellablePromise<$models.Result<$models.DirectoryContents>>}
 */
export function ListDirectory(dirPath) {
    return $Call.ByID(1744058245, dirPath).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType8($result);
    }));
}

/**
 * @param {string} targetDir
 * @param {string[]} files
 * @returns {$CancellablePromise<$models.Result<string>>}
 */
export function MoveFiles(targetDir, files) {
    return $Call.ByID(3553535974, targetDir, files).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @param {string} filePath
 * @returns {$CancellablePromise<$models.Result<string>>}
 */
export function OpenFileWithDefaultApp(filePath) {
    return $Call.ByID(2060842792, filePath).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @param {string} targetDir
 * @param {string[]} files
 * @param {boolean} cutMode
 * @returns {$CancellablePromise<$models.Result<string>>}
 */
export function PasteFiles(targetDir, files, cutMode) {
    return $Call.ByID(415346304, targetDir, files, cutMode).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

// Private type creation functions
const $$createType0 = $models.Result.createFrom($Create.Any);
const $$createType1 = $models.Result.createFrom($Create.Any);
const $$createType2 = $models.PathInfo.createFrom;
const $$createType3 = $models.Result.createFrom($$createType2);
const $$createType4 = $models.Shortcut.createFrom;
const $$createType5 = $Create.Array($$createType4);
const $$createType6 = $models.Result.createFrom($$createType5);
const $$createType7 = $models.DirectoryContents.createFrom;
const $$createType8 = $models.Result.createFrom($$createType7);
