// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * FileManagerService is a service for managing files
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * ListDirectory lists the contents of a directory.
 * @param {string} dirPath
 * @returns {$CancellablePromise<$models.Result<$models.DirectoryContents>>}
 */
export function ListDirectory(dirPath) {
    return $Call.ByID(1744058245, dirPath).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * OpenFileWithDefaultApp opens a file with the default application.
 * @param {string} filePath
 * @returns {$CancellablePromise<string>}
 */
export function OpenFileWithDefaultApp(filePath) {
    return $Call.ByID(2060842792, filePath);
}

// Private type creation functions
const $$createType0 = $models.DirectoryContents.createFrom;
const $$createType1 = $models.Result.createFrom($$createType0);
