// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../time/models.js";

export class AppError {
    /**
     * Creates a new AppError instance.
     * @param {Partial<AppError>} [$$source = {}] - The source object to create the AppError.
     */
    constructor($$source = {}) {
        if (!("code" in $$source)) {
            /**
             * @member
             * @type {ErrorCode}
             */
            this["code"] = ErrorCode.$zero;
        }
        if (!("message" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["message"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AppError instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {AppError}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AppError(/** @type {Partial<AppError>} */($$parsedSource));
    }
}

/**
 * DirectoryContents for listing directory
 */
export class DirectoryContents {
    /**
     * Creates a new DirectoryContents instance.
     * @param {Partial<DirectoryContents>} [$$source = {}] - The source object to create the DirectoryContents.
     */
    constructor($$source = {}) {
        if (!("path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["path"] = "";
        }
        if (!("files" in $$source)) {
            /**
             * @member
             * @type {FileInfo[]}
             */
            this["files"] = [];
        }
        if (!("dirCount" in $$source)) {
            /**
             * Direct children only
             * @member
             * @type {number}
             */
            this["dirCount"] = 0;
        }
        if (!("fileCount" in $$source)) {
            /**
             * Direct children only
             * @member
             * @type {number}
             */
            this["fileCount"] = 0;
        }
        if (!("directSizeBytes" in $$source)) {
            /**
             * Direct files size in bytes
             * @member
             * @type {number}
             */
            this["directSizeBytes"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DirectoryContents instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {DirectoryContents}
     */
    static createFrom($$source = {}) {
        const $$createField1_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("files" in $$parsedSource) {
            $$parsedSource["files"] = $$createField1_0($$parsedSource["files"]);
        }
        return new DirectoryContents(/** @type {Partial<DirectoryContents>} */($$parsedSource));
    }
}

/**
 * @readonly
 * @enum {string}
 */
export const ErrorCode = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    ResolvePathError: "ResolvePathError",
    ReadDirectoryError: "ReadDirectoryError",
    FileInfoError: "FileInfoError",
    FileOpenWithDefaultAppError: "FileOpenWithDefaultAppError",
    InvalidPathIndex: "InvalidPathIndex",
};

/**
 * FileInfo represents a file/directory for JSON serialization
 */
export class FileInfo {
    /**
     * Creates a new FileInfo instance.
     * @param {Partial<FileInfo>} [$$source = {}] - The source object to create the FileInfo.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("path" in $$source)) {
            /**
             * normalized absolute path
             * @member
             * @type {string}
             */
            this["path"] = "";
        }
        if (!("size" in $$source)) {
            /**
             * size in bytes
             * @member
             * @type {number}
             */
            this["size"] = 0;
        }
        if (!("isDir" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["isDir"] = false;
        }
        if (!("mode" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["mode"] = "";
        }
        if (!("modified" in $$source)) {
            /**
             * @member
             * @type {time$0.Time}
             */
            this["modified"] = null;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["extension"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FileInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {FileInfo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new FileInfo(/** @type {Partial<FileInfo>} */($$parsedSource));
    }
}

/**
 * @readonly
 * @enum {string}
 */
export const OperatingSystem = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    OSWindows: "windows",
    OSMac: "darwin",
    OSLinux: "linux",
};

export class PathInfo {
    /**
     * Creates a new PathInfo instance.
     * @param {Partial<PathInfo>} [$$source = {}] - The source object to create the PathInfo.
     */
    constructor($$source = {}) {
        if (!("fullPath" in $$source)) {
            /**
             * normalized absolute path
             * @member
             * @type {string}
             */
            this["fullPath"] = "";
        }
        if (!("parts" in $$source)) {
            /**
             * split segments for breadcrumb
             * @member
             * @type {string[]}
             */
            this["parts"] = [];
        }
        if (!("root" in $$source)) {
            /**
             * e.g., "C:\" on Windows, "/" on Linux
             * @member
             * @type {string}
             */
            this["root"] = "";
        }
        if (!("separator" in $$source)) {
            /**
             * OS-specific path separator
             * @member
             * @type {string}
             */
            this["separator"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PathInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {PathInfo}
     */
    static createFrom($$source = {}) {
        const $$createField1_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("parts" in $$parsedSource) {
            $$parsedSource["parts"] = $$createField1_0($$parsedSource["parts"]);
        }
        return new PathInfo(/** @type {Partial<PathInfo>} */($$parsedSource));
    }
}

/**
 * omitempty = omit this field if it's empty
 * @template T
 */
export class Result {
    /**
     * Creates a new Result instance.
     * @param {Partial<Result<T>>} [$$source = {}] - The source object to create the Result.
     */
    constructor($$source = {}) {
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {T | null | undefined}
             */
            this["data"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {AppError | null | undefined}
             */
            this["error"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Given creation functions for each type parameter,
     * returns a creation function for a concrete instance
     * of the generic class Result.
     * @template [T=any]
     * @param {(source: any) => T} $$createParamT
     * @returns {($$source?: any) => Result<T>}
     */
    static createFrom($$createParamT) {
        const $$createField0_0 = $$createType3($$createParamT);
        const $$createField1_0 = $$createType5;
        return ($$source = {}) => {
            let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
            if ("data" in $$parsedSource) {
                $$parsedSource["data"] = $$createField0_0($$parsedSource["data"]);
            }
            if ("error" in $$parsedSource) {
                $$parsedSource["error"] = $$createField1_0($$parsedSource["error"]);
            }
            return new Result(/** @type {Partial<Result<T>>} */($$parsedSource));
        };
    }
}

export class Shortcut {
    /**
     * Creates a new Shortcut instance.
     * @param {Partial<Shortcut>} [$$source = {}] - The source object to create the Shortcut.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["path"] = "";
        }
        if (!("logo" in $$source)) {
            /**
             * @member
             * @type {ShortcutLogo}
             */
            this["logo"] = ShortcutLogo.$zero;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Shortcut instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Shortcut}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Shortcut(/** @type {Partial<Shortcut>} */($$parsedSource));
    }
}

/**
 * @readonly
 * @enum {string}
 */
export const ShortcutLogo = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    ShortcutLogoDefault: "default",
    ShortcutLogoFolder: "folder",
    ShortcutLogoDrive: "drive",
    ShortcutLogoHome: "home",
    ShortcutLogoDocs: "documents",
    ShortcutLogoMusic: "music",
    ShortcutLogoPics: "pictures",
    ShortcutLogoVideos: "videos",
    ShortcutLogoDesktop: "desktop",
    ShortcutLogoDownloads: "downloads",
};

// Private type creation functions
const $$createType0 = FileInfo.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = $Create.Array($Create.Any);
const $$createType3 = /** @type {(...args: any[]) => any} */(($$createParamT) => $Create.Nullable($$createParamT));
const $$createType4 = AppError.createFrom;
const $$createType5 = $Create.Nullable($$createType4);
